[package]
name = "ch-09-tips-for-embedded-c-devs"
version = "0.1.0"
authors = ["Todd Nguyen <todd.nguyen@georgfischer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
